name: Build and push Docker (release)

on:
  release:
    types: [published]

jobs:
  build:
    uses: phylaxsystems/actions/.github/workflows/release-docker-ghcr-nodejs.yaml@main
    with:
      app-name: foundry-tracer-api
      dockerfile-path: Dockerfile
